kind: Cluster
name: dapr-agents
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
- role: worker
  image: kindest/node:v1.29.2@sha256:51a1434a5397193442f0be2a297b488b6c919ce8a3931be0ce822606ea5ca245
  extraPortMappings:
  - containerPort: 30080
    hostPort: 82
    protocol: TCP
  - containerPort: 30443
    hostPort: 445
    protocol: TCP
  - containerPort: 30500
    hostPort: 5500
    protocol: TCP
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16