kind: Cluster
name: dapr-agents
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.32.3@sha256:b36e76b4ad37b88539ce5e07425f77b29f73a8eaaebf3f1a8bc9c764401d118c
- role: worker
  image: kindest/node:1.32.3@sha256:b36e76b4ad37b88539ce5e07425f77b29f73a8eaaebf3f1a8bc9c764401d118c
  extraPortMappings:
  - containerPort: 30080
    hostPort: 82
    protocol: TCP
  - containerPort: 30443
    hostPort: 445
    protocol: TCP
  - containerPort: 30500
    hostPort: 5000
    protocol: TCP