apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  selector:
    app: registry
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30500
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: registry
          image: registry:2
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:5000"
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/certs/tls.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/certs/tls.key"
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
              scheme: HTTPS
          livenessProbe:
            httpGet:
              path: /v2/
              port: 5000
              scheme: HTTPS
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
            - name: tls-certs
              mountPath: "/certs"
              readOnly: true
      volumes:
        - name: registry-storage
          emptyDir: {}
        - name: tls-certs
          secret:
            secretName: registry-tls
