# generated by datamodel-codegen:
#   filename:  ChangePayload.yaml
#   timestamp: 2026-06-25T00:21:18+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel

from .ChangeSource import ChangeSource


class RecordUnknown(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class ChangePayload(BaseModel):
    source: ChangeSource
    before: RecordUnknown | None = None
    after: RecordUnknown | None = None
