# generated by datamodel-codegen:
#   filename:  ControlSignalNotification.yaml
#   timestamp: 2026-06-25T00:21:18+00:00

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from .ControlPayload import ControlPayload
from .Notification import Notification


class ControlSignalNotification(Notification):
    op: Literal["x"]
    payload: ControlPayload
    seq: Annotated[int, Field(description="The sequence number of the control signal")]
