# generated by datamodel-codegen:
#   filename:  ControlPayload.yaml
#   timestamp: 2026-06-25T00:21:18+00:00

from __future__ import annotations

from pydantic import BaseModel

from .ChangeSource import ChangeSource


class ControlPayload(BaseModel):
    source: ChangeSource
    kind: str
