# generated by datamodel-codegen:
#   filename:  Versions.yaml
#   timestamp: 2026-06-25T00:21:18+00:00

from __future__ import annotations

from enum import Enum


class Versions(Enum):
    v1 = "v1"
