# Global configuration file for workflows
# This contains shared configurations that can be referenced by individual workflow configs

dapr:
    message_bus_name: "messagepubsub"
    state_store_name: "workflowstatestore"
    state_key: "workflow_state"
    agents_registry_store_name: "workflowstatestore"
    agents_registry_key: "agents_registry"
    service_port: 8001
    grpc_port: 50001
