apiVersion: batch/v1
kind: CronJob
metadata:
  name: dapr-client
spec:
  schedule: "* * * * *"
  suspend: true # This allows us to manually trigger the job
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      backoffLimit: 4
      completions: 1
      parallelism: 1
      template:
        metadata:
          annotations:
            dapr.io/enabled: "false"
          labels:
            app: dapr-client
        spec:
          containers:
          - name: dapr-client
            env:
            - name: DEBUG
              value: "true"
            image: localhost:5001/dapr-client:latest
            imagePullPolicy: Always
          restartPolicy: Never