apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elf
  name: elf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elf
  template:
    metadata:
      labels:
        app: elf
    spec:
      containers:
      - image: registry.registry.svc.cluster.local:5000/elf:latest
        imagePullPolicy: Always
        name: elf
