apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workflow-llm
  name: workflow-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-llm
  template:
    metadata:
      labels:
        app: workflow-llm
    spec:
      containers:
      - image: localhost:5001/workflow-llm:latest
        imagePullPolicy: Always
        name: workflow-llm
