#
# Copyright 2026 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Smoke tests for Drasi unpacked event models.

Ensures that the autogenerated models are valid and importable when running
`scripts/generate-drasi-models.sh` (drasi-project/drasi-platform#437),
and that they validate messages with the expected shape.
"""

from __future__ import annotations

import pytest

try:
    from dapr_agents.ext.drasi.schemas.unpacked.ChangeNotification import (
        ChangeNotification,
    )
    from dapr_agents.ext.drasi.schemas.unpacked.ControlSignalNotification import (
        ControlSignalNotification,
    )
    from dapr_agents.ext.drasi.schemas.unpacked.ReloadHeader import ReloadHeader
    from dapr_agents.ext.drasi.schemas.unpacked.ReloadItem import ReloadItem

    DRASI_AVAILABLE = True
except ImportError:
    DRASI_AVAILABLE = False

pytestmark = pytest.mark.skipif(
    not DRASI_AVAILABLE,
    reason="dapr.ext.drasi is not available. Install the extension with: `pip install dapr-agents[drasi]`",
)


def test_change_notification_parses():
    msg = {
        "op": "i",
        "ts_ms": 0,
        "seq": 0,
        "payload": {
            "source": {"queryId": "q0", "ts_ms": 0},
            "before": {"a": 1},
            "after": {"a": 2},
        },
    }
    event = ChangeNotification.model_validate(msg)
    assert event.op.value == "i"


def test_control_signal_parses():
    msg = {
        "op": "x",
        "ts_ms": 1,
        "seq": 1,
        "payload": {"source": {"queryId": "q1", "ts_ms": 1}, "kind": "running"},
    }
    event = ControlSignalNotification.model_validate(msg)
    assert event.op == "x"


def test_reload_header_parses():
    msg = {
        "op": "h",
        "ts_ms": 2,
        "seq": 2,
    }
    event = ReloadHeader.model_validate(msg)
    assert event.op == "h"


def test_reload_item_parses():
    msg = {
        "op": "r",
        "ts_ms": 3,
        "seq": 3,
        "payload": {
            "source": {"queryId": "q3", "ts_ms": 3},
            "before": {"b": 3},
            "after": {"b": 4},
        },
    }
    event = ReloadItem.model_validate(msg)
    assert event.op == "r"
