#
# Copyright 2026 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Smoke tests for Drasi unpacked event models.

Ensures that the autogenerated models are valid and importable when running
`scripts/generate-drasi-models.sh` (drasi-project/drasi-platform#437),
and that they validate messages with the expected shape.
"""

from __future__ import annotations

from dapr_agents.ext.drasi.schemas.unpacked.ChangeNotification import ChangeNotification  # type: ignore[import-not-found]
from dapr_agents.ext.drasi.schemas.unpacked.ControlSignalNotification import (  # type: ignore[import-not-found]
    ControlSignalNotification,
)


def test_change_notification_parses():
    msg = {
        "op": "i",
        "ts_ms": 1,
        "seq": 1,
        "payload": {"source": {"queryId": "q1", "ts_ms": 1}, "after": {"x": 1}},
    }
    event = ChangeNotification.model_validate(msg)
    assert event.op.value == "i"


def test_control_signal_parses():
    msg = {
        "op": "x",
        "ts_ms": 1,
        "seq": 1,
        "payload": {"source": {"queryId": "q1", "ts_ms": 1}, "kind": "running"},
    }
    event = ControlSignalNotification.model_validate(msg)
    assert event.op == "x"
