#
# Copyright 2026 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Smoke tests for Drasi unpacked event models.

Ensures that the autogenerated models are valid and importable when running
`scripts/regen-drasi-models.sh` (drasi-project/drasi-platform#437),
and that they validate messages with the expected shape.

Only tests models that are actually used to minimize the risk of schema drift
impacting extension development in Dapr Agents.
"""

from __future__ import annotations

import pytest

try:
    from dapr_agents.ext.drasi.schemas.unpacked.ChangeNotification import (
        ChangeNotification,
        Op,
    )

    DRASI_AVAILABLE = True
except ImportError:
    DRASI_AVAILABLE = False

pytestmark = pytest.mark.skipif(
    not DRASI_AVAILABLE,
    reason=(
        "dapr-agents-ext-drasi is not available. "
        "To run these tests, install the extension with: "
        "`uv sync --group test --extra drasi`"
    ),
)


def test_change_notification_parses():
    msg = {
        "op": "u",
        "ts_ms": 0,
        "seq": 0,
        "payload": {
            "source": {"queryId": "q0", "ts_ms": 0},
            "before": {"a": 1},
            "after": {"a": 2},
        },
    }
    event = ChangeNotification.model_validate(msg)
    assert event.op == Op.u
